const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const mainSource = fs.readFileSync(path.join(__dirname, 'main.cjs'), 'utf8')

test('thread continuation prompt is action-oriented and avoids fixed file checklists', () => {
  assert.match(mainSource, /## Known Navigation Hints/)
  assert.match(mainSource, /## Discarded Prior Conclusions/)
  assert.match(mainSource, /仅作追溯线索；不要假设新对话一定能读取旧线程/)
  assert.match(mainSource, /不要要求新对话按固定文件清单阅读代码/)
  assert.match(mainSource, /不要记录旧对话中某一时刻的临时仓库状态/)
  assert.match(mainSource, /旧对话中已完成或曾修改过/)
  assert.match(mainSource, /Keep at most 6-8 items/)
  assert.match(mainSource, /不要复制 AGENTS\.md、系统\/开发者指令或仓库通用规范/)
  assert.match(mainSource, /请先完整理解以上接续摘要，把它作为当前对话上下文；如果本条消息没有新的明确任务，请等待用户下一步指令。/)
  assert.match(mainSource, /Only include interfaces, params, fields, or contracts/)
  assert.match(mainSource, /Only include prior conclusions that would directly affect the next step/)
  assert.match(mainSource, /Validation status, skipped commands, and manual verification expectations belong in Verification Status, not here/)
  assert.match(mainSource, /Open Items lists concrete pending work; Suggested Next Step gives strategy/)
  assert.match(mainSource, /The current request to generate this continuation summary is not the current goal/)
  assert.match(mainSource, /trace back to the latest substantive non-continuation, non-summary-review task/)
  assert.doesNotMatch(mainSource, /若用户已经给出明确任务，请基于摘要和当前仓库继续处理/)
  assert.doesNotMatch(mainSource, /## 给新对话的启动指令/)
  assert.doesNotMatch(mainSource, /## 相关文件与位置/)
  assert.doesNotMatch(mainSource, /列出后续最可能需要阅读或修改的文件/)
  assert.doesNotMatch(mainSource, /- 是否允许直接改代码。/)
  assert.doesNotMatch(mainSource, /- 包管理器要求。/)
})

test('generated continuation and exploration prompts derive response language from user context', () => {
  assert.match(mainSource, /Use the English template below as the canonical structure/)
  assert.match(mainSource, /If the target response language is not English, translate every heading and all body text/)
  assert.match(mainSource, /## Response Language/)
  assert.match(mainSource, /## Current Goal/)
  assert.match(mainSource, /## Suggested Next Step/)
  assert.doesNotMatch(mainSource, /# 接续摘要/)
  assert.doesNotMatch(mainSource, /## 当前目标/)
  assert.match(mainSource, /不要根据本段接续说明的语言决定回答语言/)
  assert.doesNotMatch(mainSource, /不要根据本包装文案或 Sidecar UI 语言决定回答语言/)
  assert.match(mainSource, /不要根据本内部提示词、候选标签或 Sidecar UI 语言决定/)
  assert.match(mainSource, /候选材料的语言不是最终回答语言依据/)
  assert.match(mainSource, /用户明确要求、原始任务、历史对话上下文和目标产物/)
  assert.doesNotMatch(mainSource, /使用用户原始语言回答。/)
})
