const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const rootDir = path.join(__dirname, '..')
const settingsPanelSource = fs.readFileSync(path.join(__dirname, 'components/panels/SettingsPanel.vue'), 'utf8')
const envSource = fs.readFileSync(path.join(__dirname, 'env.d.ts'), 'utf8')
const mainSource = fs.readFileSync(path.join(rootDir, 'electron/main.cjs'), 'utf8')
const preloadSource = fs.readFileSync(path.join(rootDir, 'electron/preload.cjs'), 'utf8')

test('settings footer keeps brand and GitHub while version moves to the update row', () => {
  assert.match(settingsPanelSource, /import packageJson from '..\/..\/..\/package\.json'/)
  assert.match(settingsPanelSource, /const appVersion = packageJson\.version/)
  assert.match(settingsPanelSource, /Codex Sidecar/)
  assert.match(settingsPanelSource, /t\('settings\.version'\)/)
  assert.match(settingsPanelSource, /v\{\{ appVersion \}\}/)
  assert.match(settingsPanelSource, /t\('settings\.upToDate'\)/)
  assert.match(settingsPanelSource, /t\('settings\.restartUpdate'\)/)
  assert.doesNotMatch(settingsPanelSource, /<footer[\s\S]*v\{\{ appVersion \}\}[\s\S]*<\/footer>/)
  assert.match(settingsPanelSource, /window\.sidecar\.openGitHub\(\)/)
  assert.match(settingsPanelSource, /window\.sidecar\.getUpdateState\(\)/)
  assert.match(settingsPanelSource, /window\.sidecar\.installUpdate\(\)/)
  assert.match(settingsPanelSource, /window\.sidecar\.onUpdateStateChanged\(/)

  assert.match(mainSource, /const \{ version: APP_VERSION \} = require\('\.\.\/package\.json'\)/)
  assert.doesNotMatch(mainSource, /const APP_VERSION = ['"]/)
  assert.match(mainSource, /const APP_REPOSITORY_URL = 'https:\/\/github\.com\/eshengsky\/Codex-Sidecar'/)
  assert.match(mainSource, /ipcMain\.handle\('sidecar:openGitHub'[\s\S]*shell\.openExternal\(APP_REPOSITORY_URL\)/)
  assert.match(mainSource, /ipcMain\.handle\('sidecar:getUpdateState'[\s\S]*getUpdateState\(\)/)
  assert.match(mainSource, /ipcMain\.handle\('sidecar:installUpdate'[\s\S]*installUpdate\(\)/)

  assert.match(preloadSource, /openGitHub: \(\) => ipcRenderer\.invoke\('sidecar:openGitHub'\)/)
  assert.match(preloadSource, /getUpdateState: \(\) => ipcRenderer\.invoke\('sidecar:getUpdateState'\)/)
  assert.match(preloadSource, /installUpdate: \(\) => ipcRenderer\.invoke\('sidecar:installUpdate'\)/)
  assert.match(preloadSource, /onUpdateStateChanged: callback =>/)
  assert.match(envSource, /openGitHub: \(\) => Promise<boolean>/)
  assert.match(envSource, /getUpdateState: \(\) => Promise<SidecarUpdateState>/)
  assert.match(envSource, /installUpdate: \(\) => Promise<\{ ok: boolean, error\?: string \}>/)
  assert.match(envSource, /onUpdateStateChanged: \(callback: \(state: SidecarUpdateState\) => void\) => \(\) => void/)
})
