const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const test = require('node:test')

const rootDir = path.join(__dirname, '..')
const packageJson = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'))
const settingsPanelSource = fs.readFileSync(path.join(__dirname, 'components/panels/SettingsPanel.vue'), 'utf8')
const settingsPanelTemplate = settingsPanelSource.split('</template>')[0]
const envSource = fs.readFileSync(path.join(__dirname, 'env.d.ts'), 'utf8')
const mainSource = fs.readFileSync(path.join(rootDir, 'electron/main.cjs'), 'utf8')
const preloadSource = fs.readFileSync(path.join(rootDir, 'electron/preload.cjs'), 'utf8')
const autoUpdateSource = fs.readFileSync(path.join(rootDir, 'electron/auto-update.cjs'), 'utf8')
const i18nSource = fs.readFileSync(path.join(__dirname, 'i18n/messages.ts'), 'utf8')

test('settings footer keeps brand and GitHub while version moves to the update row', () => {
  assert.match(settingsPanelSource, /import packageJson from '..\/..\/..\/package\.json'/)
  assert.match(settingsPanelSource, /const appVersion = packageJson\.version/)
  assert.match(settingsPanelSource, /Codex Sidecar/)
  assert.match(settingsPanelSource, /<span>MIT License<\/span>/)
  assert.equal(packageJson.license, 'MIT')
  assert.match(settingsPanelSource, /t\('settings\.version'\)/)
  assert.match(settingsPanelSource, /v\{\{ appVersion \}\}/)
  assert.match(settingsPanelSource, /t\('settings\.upToDate'\)/)
  assert.match(settingsPanelSource, /t\('settings\.restartUpdate'\)/)
  assert.doesNotMatch(settingsPanelSource, /<footer[\s\S]*v\{\{ appVersion \}\}[\s\S]*<\/footer>/)
  assert.match(settingsPanelSource, /window\.sidecar\.openGitHub\(\)/)
  assert.match(settingsPanelSource, /window\.sidecar\.getUpdateState\(\)/)
  assert.match(settingsPanelSource, /window\.sidecar\.installUpdate\(\)/)
  assert.match(settingsPanelSource, /window\.sidecar\.onUpdateStateChanged\(/)

  assert.match(mainSource, /const \{ version: APP_VERSION \} = require\('\.\.\/package\.json'\)/)
  assert.doesNotMatch(mainSource, /const APP_VERSION = ['"]/)
  assert.match(mainSource, /const APP_REPOSITORY_URL = 'https:\/\/github\.com\/eshengsky\/Codex-Sidecar'/)
  assert.match(mainSource, /ipcMain\.handle\('sidecar:openGitHub'[\s\S]*shell\.openExternal\(APP_REPOSITORY_URL\)/)
  assert.match(mainSource, /ipcMain\.handle\('sidecar:getUpdateState'[\s\S]*getUpdateState\(\)/)
  assert.match(mainSource, /ipcMain\.handle\('sidecar:installUpdate'[\s\S]*installUpdate\(\)/)

  assert.match(preloadSource, /openGitHub: \(\) => ipcRenderer\.invoke\('sidecar:openGitHub'\)/)
  assert.match(preloadSource, /getUpdateState: \(\) => ipcRenderer\.invoke\('sidecar:getUpdateState'\)/)
  assert.match(preloadSource, /installUpdate: \(\) => ipcRenderer\.invoke\('sidecar:installUpdate'\)/)
  assert.match(preloadSource, /onUpdateStateChanged: callback =>/)
  assert.match(envSource, /openGitHub: \(\) => Promise<boolean>/)
  assert.match(envSource, /getUpdateState: \(\) => Promise<SidecarUpdateState>/)
  assert.match(envSource, /installUpdate: \(\) => Promise<\{ ok: boolean, error\?: string \}>/)
  assert.match(envSource, /onUpdateStateChanged: \(callback: \(state: SidecarUpdateState\) => void\) => \(\) => void/)
})

test('auto update checks run in the background while settings only renders state', () => {
  assert.match(autoUpdateSource, /const AUTO_UPDATE_CHECK_INTERVAL_MS = 4 \* 60 \* 60 \* 1000/)
  assert.match(autoUpdateSource, /const AUTO_UPDATE_ACTIVE_CHECK_INTERVAL_MS = 60 \* 60 \* 1000/)
  assert.match(autoUpdateSource, /setInterval\(\(\) => \{/)
  assert.match(autoUpdateSource, /state\.status === 'checking'[\s\S]*state\.status === 'downloading'/)
  assert.match(autoUpdateSource, /autoUpdater\.on\('download-progress'/)
  assert.match(autoUpdateSource, /status: 'downloading'/)
  assert.match(autoUpdateSource, /status: 'not-available'/)
  assert.match(autoUpdateSource, /const maybeCheckForUpdatesAfterIdle = \(\) => \{/)

  assert.match(mainSource, /scheduleAutoUpdateCheck\(\)/)
  assert.match(mainSource, /maybeCheckForUpdatesAfterIdle\(\)/)
  assert.match(mainSource, /powerMonitor\.on\('resume'/)
  assert.doesNotMatch(preloadSource, /checkForUpdates/)
  assert.doesNotMatch(settingsPanelSource, /checkForUpdates/)

  assert.match(settingsPanelSource, /const updateStatusText = computed/)
  assert.match(settingsPanelSource, /settings\.checkingUpdate/)
  assert.match(settingsPanelSource, /settings\.updating/)
  assert.match(settingsPanelSource, /settings\.updateCheckFailed/)
  assert.match(settingsPanelSource, /status === 'not-available'/)
  assert.doesNotMatch(settingsPanelTemplate, /settings\.upToDate/)

  assert.match(envSource, /'idle' \| 'checking' \| 'downloading' \| 'downloaded' \| 'not-available' \| 'error'/)
  assert.match(i18nSource, /checkingUpdate: 'Checking\.\.\.'/)
  assert.match(i18nSource, /updating: 'Updating\.\.\.'/)
  assert.match(i18nSource, /updateCheckFailed: 'Check failed'/)
  assert.match(i18nSource, /checkingUpdate: '正在检查\.\.\.'/)
  assert.match(i18nSource, /updating: '正在更新\.\.\.'/)
  assert.match(i18nSource, /updateCheckFailed: '检查失败'/)
})
